feat: 🎸 added a prop for sqformIconButton for teal icon
SelectQuoteLabs/SQForm pull request #291
Opened 2021-06-01 08:17 UTC by saadurrehman-selectquote

feat: 🎸 added a prop for sqformIconButton for teal icon

added a prop for sqformIconButton for teal icon

✅ Closes: 288

https://www.loom.com/share/17baf5febaaf4a6689ea0dc871b6f854

2021-06-01 08:47 UTC, Muhammad-Waseem413 approved these changes

2021-06-01 16:20 UTC, SeanGroff commented
Thank you @saadurrehman-selectquote for contributing to this code enhancement!
Can you update the test to account for this code change, please?
https://github.com/SelectQuoteLabs/SQForm/blob/master/stories/__tests__/SQFormIconButton.stories.test.js

2021-06-01 16:21 UTC, SeanGroff requested changes
I've requested @saadurrehman-selectquote update the test for this component to account for the new code changes
https://github.com/SelectQuoteLabs/SQForm/blob/master/stories/__tests__/SQFormIconButton.stories.test.js

2021-06-01 16:38 UTC, 20BBrown14 approved these changes

2021-06-02 09:58 UTC, saadurrehman-selectquote commented
> I've requested @saadurrehman-selectquote update the test for this component to account for the new code changes
> https://github.com/SelectQuoteLabs/SQForm/blob/master/stories/__tests__/SQFormIconButton.stories.test.js

Updated

2021-06-02 13:37 UTC, merged